[package]
name = "muscli"
version = "0.1.0"
authors = ["Connor Perkins <cperkin4@gmu.edu>"]
edition = "2018"

[dependencies]
tui = "0.5.1"
termion = "1.5.1"
id3 = "0.3.0"
glob = "0.3.0"
failure = "0.1.5"
fmod = "0.10.1"
